# Generated by Django 5.1.2 on 2024-10-25 16:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iklan', '0001_initial'),
        ('rumah', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iklanentry',
            name='id',
        ),
        migrations.AddField(
            model_name='iklanentry',
            name='id_rumah',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='iklanentry',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='iklanentry',
            name='rumah',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rumah.house'),
        ),
    ]
