# Generated by Django 5.1.2 on 2024-10-27 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iklan', '0002_remove_iklanentry_id_iklanentry_id_rumah_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iklanentry',
            name='banner',
            field=models.ImageField(upload_to='static/img/'),
        ),
    ]
