# Generated by Django 5.1.2 on 2024-10-27 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HouseHuntAuth', '0001_initial'),
        ('iklan', '0003_alter_iklanentry_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iklanentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HouseHuntAuth.seller'),
        ),
    ]
