# Generated by Django 5.1.2 on 2024-10-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iklan', '0004_alter_iklanentry_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iklanentry',
            old_name='user',
            new_name='seller',
        ),
        migrations.RemoveField(
            model_name='iklanentry',
            name='id_rumah',
        ),
        migrations.AddField(
            model_name='iklanentry',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
