# Generated by Django 5.1.2 on 2024-10-26 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('HouseHuntAuth', '0001_initial'),
        ('rumah', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('starting_price', models.PositiveIntegerField()),
                ('current_price', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('highest_buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HouseHuntAuth.buyer')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rumah.house')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HouseHuntAuth.seller')),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.auction')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HouseHuntAuth.buyer')),
            ],
        ),
    ]
