# Generated by Django 5.1.2 on 2024-10-26 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_alter_auction_id_alter_bid_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='description',
        ),
    ]
