# Generated by Django 5.1.2 on 2024-10-27 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HouseHuntAuth', '0001_initial'),
        ('auction', '0003_remove_auction_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='highest_buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HouseHuntAuth.buyer'),
        ),
    ]
