# Generated by Django 5.1.2 on 2024-10-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diskusi', '0003_remove_post_likes_remove_post_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='star',
            field=models.IntegerField(default=0),
        ),
    ]
