# Generated by Django 5.1.2 on 2024-10-27 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diskusi', '0004_comment_star'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default='Anonymous', max_length=150),
        ),
    ]
