# Generated by Django 5.1.2 on 2024-10-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diskusi', '0005_comment_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='likedreply',
            name='reply',
        ),
        migrations.RemoveField(
            model_name='likedreply',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='author',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='parent_comment',
        ),
        migrations.AddField(
            model_name='reply',
            name='name',
            field=models.CharField(default='Anonymous', max_length=150),
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='reply',
            name='body',
            field=models.CharField(max_length=400),
        ),
        migrations.DeleteModel(
            name='LikedComment',
        ),
        migrations.DeleteModel(
            name='LikedReply',
        ),
    ]
