# Generated by Django 5.1.2 on 2024-10-27 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diskusi', '0006_remove_comment_likes_remove_likedreply_reply_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='parent_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='diskusi.comment'),
        ),
    ]
