# Generated by Django 5.1.2 on 2024-10-27 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HouseHuntAuth', '0002_seller_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='stars',
            field=models.FloatField(default=0),
        ),
    ]
